// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages all OS-level UI interactions (menus, windows, tray).
 * It is the main entry point for all display-related operations.
 */
export interface Service {
}
