// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages all OS-level UI interactions (menus, windows, tray).
 * It is the main entry point for all display-related operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as i18n$0 from "../i18n/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * OpenWindow creates and shows a new webview window.
 * This function is callable from the frontend.
 */
export function OpenWindow(name: string, options: application$0.WebviewWindowOptions): $CancellablePromise<void> {
    return $Call.ByID(2690719559, name, options);
}

/**
 * SelectDirectory opens a directory selection dialog and returns the selected path.
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3446753642);
}

/**
 * Setup initializes the display service with the application instance and other core services.
 */
export function Setup(app: application$0.App | null, configService: config$0.Service | null, i18nService: i18n$0.Service | null): $CancellablePromise<void> {
    return $Call.ByID(4003022588, app, configService, i18nService);
}

export function ShowEnvironmentDialog(): $CancellablePromise<void> {
    return $Call.ByID(1667227975);
}
