// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ServiceDisplay from "./servicedisplay.js";
export {
    ServiceDisplay
};
