// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages all OS-level UI interactions (menus, windows, tray).
 * It is the main entry point for all display-related operations
 * and is bound to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * OpenWindow creates and shows a new webview window.
 * This function is callable from the frontend.
 */
export function OpenWindow(app: application$0.App | null, name: string, options: application$0.WebviewWindowOptions): $CancellablePromise<void> {
    return $Call.ByID(3731760391, app, name, options);
}

/**
 * Startup is called by Wails when the application starts.
 * It orchestrates the setup of all UI elements.
 */
export function Setup(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4134194364, app);
}
