// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * BuildMenu applies settings to the main application object
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function BuildMenu(app) {
    return $Call.ByID(3966317070, app);
}

/**
 * @param {application$0.App | null} app
 * @param {string} name
 * @param {application$0.WebviewWindowOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OpenWindow(app, name, options) {
    return $Call.ByID(1997180639, app, name, options);
}
