// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bool is a `bool` that can be unset
 */
export type Bool = Var<boolean>;

/**
 * Var is a variable that can be set, unset and queried for its state.
 */
export interface Var<T> {
}
