// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as template$1 from "./template/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as template$0 from "../../../../../text/template/models.js";

/**
 * Bundle stores a set of messages and pluralization rules.
 * Most applications only need a single bundle
 * that is initialized early in the application's lifecycle.
 * It is not goroutine safe to modify the bundle while Localizers
 * are reading from it.
 */
export interface Bundle {
}

/**
 * LocalizeConfig configures a call to the Localize method on Localizer.
 */
export interface LocalizeConfig {
    /**
     * MessageID is the id of the message to lookup.
     * This field is ignored if DefaultMessage is set.
     */
    "MessageID": string;

    /**
     * TemplateData is the data passed when executing the message's template.
     * If TemplateData is nil and PluralCount is not nil, then the message template
     * will be executed with data that contains the plural count.
     */
    "TemplateData": any;

    /**
     * PluralCount determines which plural form of the message is used.
     */
    "PluralCount": any;

    /**
     * DefaultMessage is used if the message is not found in any message files.
     */
    "DefaultMessage": Message | null;

    /**
     * Funcs is used to configure a template.TextParser if TemplateParser is not set.
     */
    "Funcs": template$0.FuncMap;

    /**
     * The TemplateParser to use for parsing templates.
     * If one is not set, a template.TextParser is used (configured with Funcs if it is set).
     */
    "TemplateParser": template$1.Parser;
}

/**
 * Message is a string that can be localized.
 */
export interface Message {
    /**
     * ID uniquely identifies the message.
     */
    "ID": string;

    /**
     * Hash uniquely identifies the content of the message
     * that this message was translated from.
     */
    "Hash": string;

    /**
     * Description describes the message to give additional
     * context to translators that may be relevant for translation.
     */
    "Description": string;

    /**
     * LeftDelim is the left Go template delimiter.
     */
    "LeftDelim": string;

    /**
     * RightDelim is the right Go template delimiter.
     */
    "RightDelim": string;

    /**
     * Zero is the content of the message for the CLDR plural form "zero".
     */
    "Zero": string;

    /**
     * One is the content of the message for the CLDR plural form "one".
     */
    "One": string;

    /**
     * Two is the content of the message for the CLDR plural form "two".
     */
    "Two": string;

    /**
     * Few is the content of the message for the CLDR plural form "few".
     */
    "Few": string;

    /**
     * Many is the content of the message for the CLDR plural form "many".
     */
    "Many": string;

    /**
     * Other is the content of the message for the CLDR plural form "other".
     */
    "Other": string;
}
