// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Tag represents a BCP 47 language tag. It is used to specify an instance of a
 * specific language or locale. All language tag values are guaranteed to be
 * well-formed.
 */
export type Tag = string;
