// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds the resolved paths and user-configurable settings for the application.
 */
export class Config {
    /**
     * --- Storable Settings (persisted in config.json) ---
     */
    "defaultRoute"?: string;
    "features"?: string[];
    "language"?: string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField1_0($$parsedSource["features"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * Service provides access to the application's configuration.
 */
export class Service {

    /** Creates a new Service instance. */
    constructor($$source: Partial<Service> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     */
    static createFrom($$source: any = {}): Service {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service($$parsedSource as Partial<Service>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
