// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config holds the resolved paths and user-configurable settings for the application.
 */
export interface Config {
    /**
     * --- Storable Settings (persisted in config.json) ---
     */
    "defaultRoute"?: string;
    "features"?: string[] | null;
    "language"?: string;
}

/**
 * Service provides access to the application's configuration.
 */
export interface Service {
}
