// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides access to the application's configuration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnableFeature adds a feature to the list of enabled features and saves the config.
 */
export function EnableFeature(feature: string): $CancellablePromise<void> {
    return $Call.ByID(2749453610, feature);
}

/**
 * Get returns the loaded configuration.
 */
export function Get(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(1956316061);
}

/**
 * IsFeatureEnabled checks if a given feature is enabled in the configuration.
 */
export function IsFeatureEnabled(feature: string): $CancellablePromise<boolean> {
    return $Call.ByID(280175744, feature);
}

/**
 * Save writes the current configuration to config.json.
 */
export function Save(): $CancellablePromise<void> {
    return $Call.ByID(2065272110);
}
