// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DisplayConfigService from "./displayconfigservice.js";
export {
    DisplayConfigService
};
