// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides access to the application's configuration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the loaded configuration.
 */
export function Get(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(2457248349).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Save writes the current configuration to config.json.
 */
export function Save(): $CancellablePromise<void> {
    return $Call.ByID(3151211502);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
