// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides internationalization and localization.
 * It is the concrete implementation for the i18n service.
 */
export interface Service {
}
