// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides internationalization and localization.
 * It is the concrete implementation for the i18n service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as i18n$0 from "../../../../../nicksnyder/go-i18n/v2/i18n/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as language$0 from "../../../../../../golang.org/x/text/language/models.js";

/**
 * AvailableLanguages returns the list of available languages.
 */
export function AvailableLanguages(): $CancellablePromise<language$0.Tag[] | null> {
    return $Call.ByID(1795050163);
}

/**
 * Bundle returns the underlying i18n.Bundle.
 */
export function Bundle(): $CancellablePromise<i18n$0.Bundle | null> {
    return $Call.ByID(3872115765);
}

/**
 * GetAllMessages returns all messages for a given language as a map.
 * This is intended for frontend pre-loading to enable synchronous lookups.
 */
export function GetAllMessages(lang: string): $CancellablePromise<{ [_: string]: string } | null> {
    return $Call.ByID(3739048462, lang);
}

/**
 * SetLanguage changes the active language for translations.
 */
export function SetLanguage(lang: string): $CancellablePromise<void> {
    return $Call.ByID(1354488549, lang);
}

/**
 * Translate a message by its ID using the configured language.
 */
export function Translate(messageID: string): $CancellablePromise<string> {
    return $Call.ByID(1347054469, messageID);
}

/**
 * TranslateWithConfig translates a message using a LocalizeConfig.
 */
export function TranslateWithConfig(lc: i18n$0.LocalizeConfig | null): $CancellablePromise<string> {
    return $Call.ByID(1844970395, lc);
}
