// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages the documentation display and serving of assets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as display$0 from "../core/display/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * OpenDocsWindow opens a new window with the documentation.
 */
export function OpenDocsWindow(...path: string[]): $CancellablePromise<void> {
    return $Call.ByID(2515669291, path);
}

/**
 * Setup injects the required dependencies into the service.
 */
export function Setup(app: application$0.App | null, displayService: display$0.Service | null): $CancellablePromise<void> {
    return $Call.ByID(3350268793, app, displayService);
}
