site_name: Lethean Documentation
copyright: LetheanVPN &copy; EUPL-1.2 &mdash; 2017 to &infin; and beyond
theme:
  name: material
#  custom_dir: overrides
  font: 
    text: "Roboto"
    code: "Roboto Mono"
  language: en
  icon:
    repo: fontawesome/brands/git-alt
    code: octicons/alert-24
    edit: material/pencil 
    view: material/eye

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy

extra:
  generator: false
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search:
      lang:
        - en
  
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
