// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages different blockchain network implementations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * FetchBlockData routes the call to the active network.
 */
export function FetchBlockData(identifier: string): $CancellablePromise<string> {
    return $Call.ByID(3104904158, identifier);
}

/**
 * Install can be used to download and set up blockchain binaries.
 */
export function Install(networkID: string): $CancellablePromise<void> {
    return $Call.ByID(1064404694, networkID);
}

/**
 * Start activates a specific blockchain network.
 */
export function Start(networkID: string): $CancellablePromise<void> {
    return $Call.ByID(3778425957, networkID);
}
