// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as u$0 from "../../../../../leaanthony/u/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../../log/slog/models.js";

export interface App {
    /**
     * Manager pattern for organized API
     */
    "Window": WindowManager | null;
    "ContextMenu": ContextMenuManager | null;
    "KeyBinding": KeyBindingManager | null;
    "Browser": BrowserManager | null;
    "Env": EnvironmentManager | null;
    "Dialog": DialogManager | null;
    "Event": EventManager | null;
    "Menu": MenuManager | null;
    "Screen": ScreenManager | null;
    "Clipboard": ClipboardManager | null;
    "SystemTray": SystemTrayManager | null;
    "Logger": slog$0.Logger | null;
}

export enum BackdropType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Auto = 0,
    None = 1,
    Mica = 2,
    Acrylic = 3,
    Tabbed = 4,
};

export enum BackgroundType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    BackgroundTypeSolid = 0,
    BackgroundTypeTransparent = 1,
    BackgroundTypeTranslucent = 2,
};

/**
 * BrowserManager manages browser-related operations
 */
export interface BrowserManager {
}

export enum ButtonState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ButtonEnabled = 0,
    ButtonDisabled = 1,
    ButtonHidden = 2,
};

/**
 * ClipboardManager manages clipboard operations
 */
export interface ClipboardManager {
}

/**
 * ContextMenuManager manages all context menu operations
 */
export interface ContextMenuManager {
}

export enum CoreWebView2PermissionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CoreWebView2PermissionStateDefault = 0,
    CoreWebView2PermissionStateAllow = 1,
    CoreWebView2PermissionStateDeny = 2,
};

/**
 * DialogManager manages dialog-related operations
 */
export interface DialogManager {
}

export enum DragEffect {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * DragEffectNone is used to indicate that the drop target cannot accept the data.
     */
    DragEffectNone = 1,

    /**
     * DragEffectCopy is used to indicate that the data is copied to the drop target.
     */
    DragEffectCopy = 2,

    /**
     * DragEffectMove is used to indicate that the data is removed from the drag source.
     */
    DragEffectMove = 3,

    /**
     * DragEffectLink is used to indicate that a link to the original data is established.
     */
    DragEffectLink = 4,
};

/**
 * EnvironmentManager manages environment-related operations
 */
export interface EnvironmentManager {
}

/**
 * EventManager manages event-related operations
 */
export interface EventManager {
}

/**
 * KeyBindingManager manages all key binding operations
 */
export interface KeyBindingManager {
}

/**
 * LinuxWindow specific to Linux windows
 */
export interface LinuxWindow {
    /**
     * Icon Sets up the icon representing the window. This icon is used when the window is minimized
     * (also known as iconified).
     */
    "Icon": string | null;

    /**
     * WindowIsTranslucent sets the window's background to transparent when enabled.
     */
    "WindowIsTranslucent": boolean;

    /**
     * WebviewGpuPolicy used for determining the hardware acceleration policy for the webview.
     *   - WebviewGpuPolicyAlways
     *   - WebviewGpuPolicyOnDemand
     *   - WebviewGpuPolicyNever
     * 
     * Due to https://github.com/wailsapp/wails/issues/2977, if options.Linux is nil
     * in the call to wails.Run(), WebviewGpuPolicy is set by default to WebviewGpuPolicyNever.
     * Client code may override this behavior by passing a non-nil Options and set
     * WebviewGpuPolicy as needed.
     */
    "WebviewGpuPolicy": WebviewGpuPolicy;

    /**
     * WindowDidMoveDebounceMS is the debounce time in milliseconds for the WindowDidMove event
     */
    "WindowDidMoveDebounceMS": number;

    /**
     * Menu is the window's menu
     */
    "Menu": Menu | null;
}

/**
 * MacAppearanceType is a type of Appearance for Cocoa windows
 */
export enum MacAppearanceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * DefaultAppearance uses the default system value
     */
    DefaultAppearance = "",

    /**
     * NSAppearanceNameAqua - The standard light system appearance.
     */
    NSAppearanceNameAqua = "NSAppearanceNameAqua",

    /**
     * NSAppearanceNameDarkAqua - The standard dark system appearance.
     */
    NSAppearanceNameDarkAqua = "NSAppearanceNameDarkAqua",

    /**
     * NSAppearanceNameVibrantLight - The light vibrant appearance
     */
    NSAppearanceNameVibrantLight = "NSAppearanceNameVibrantLight",

    /**
     * NSAppearanceNameAccessibilityHighContrastAqua - A high-contrast version of the standard light system appearance.
     */
    NSAppearanceNameAccessibilityHighContrastAqua = "NSAppearanceNameAccessibilityHighContrastAqua",

    /**
     * NSAppearanceNameAccessibilityHighContrastDarkAqua - A high-contrast version of the standard dark system appearance.
     */
    NSAppearanceNameAccessibilityHighContrastDarkAqua = "NSAppearanceNameAccessibilityHighContrastDarkAqua",

    /**
     * NSAppearanceNameAccessibilityHighContrastVibrantLight - A high-contrast version of the light vibrant appearance.
     */
    NSAppearanceNameAccessibilityHighContrastVibrantLight = "NSAppearanceNameAccessibilityHighContrastVibrantLight",

    /**
     * NSAppearanceNameAccessibilityHighContrastVibrantDark - A high-contrast version of the dark vibrant appearance.
     */
    NSAppearanceNameAccessibilityHighContrastVibrantDark = "NSAppearanceNameAccessibilityHighContrastVibrantDark",
};

/**
 * MacBackdrop is the backdrop type for macOS
 */
export enum MacBackdrop {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * MacBackdropNormal - The default value. The window will have a normal opaque background.
     */
    MacBackdropNormal = 0,

    /**
     * MacBackdropTransparent - The window will have a transparent background, with the content underneath it being visible
     */
    MacBackdropTransparent = 1,

    /**
     * MacBackdropTranslucent - The window will have a translucent background, with the content underneath it being "fuzzy" or "frosted"
     */
    MacBackdropTranslucent = 2,

    /**
     * MacBackdropLiquidGlass - The window will use Apple's Liquid Glass effect (macOS 15.0+ with fallback to translucent)
     */
    MacBackdropLiquidGlass = 3,
};

/**
 * MacLiquidGlass contains configuration for the Liquid Glass effect
 */
export interface MacLiquidGlass {
    /**
     * Style of the glass effect
     */
    "Style": MacLiquidGlassStyle;

    /**
     * Material to use for NSVisualEffectView (when NSGlassEffectView is not available)
     * Set to NSVisualEffectMaterialAuto to use automatic selection based on Style
     */
    "Material": NSVisualEffectMaterial;

    /**
     * Corner radius for the glass effect (0 for square corners)
     */
    "CornerRadius": number;

    /**
     * Tint color for the glass (optional, nil for no tint)
     */
    "TintColor": RGBA | null;

    /**
     * Group identifier for merging multiple glass windows
     */
    "GroupID": string;

    /**
     * Spacing between grouped glass elements (in points)
     */
    "GroupSpacing": number;
}

/**
 * MacLiquidGlassStyle defines the style of the Liquid Glass effect
 */
export enum MacLiquidGlassStyle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * LiquidGlassStyleAutomatic - System determines the best style
     */
    LiquidGlassStyleAutomatic = 0,

    /**
     * LiquidGlassStyleLight - Light glass appearance
     */
    LiquidGlassStyleLight = 1,

    /**
     * LiquidGlassStyleDark - Dark glass appearance
     */
    LiquidGlassStyleDark = 2,

    /**
     * LiquidGlassStyleVibrant - Vibrant glass with enhanced effects
     */
    LiquidGlassStyleVibrant = 3,
};

/**
 * MacTitleBar contains options for the Mac titlebar
 */
export interface MacTitleBar {
    /**
     * AppearsTransparent will make the titlebar transparent
     */
    "AppearsTransparent": boolean;

    /**
     * Hide will hide the titlebar
     */
    "Hide": boolean;

    /**
     * HideTitle will hide the title
     */
    "HideTitle": boolean;

    /**
     * FullSizeContent will extend the window content to the full size of the window
     */
    "FullSizeContent": boolean;

    /**
     * UseToolbar will use a toolbar instead of a titlebar
     */
    "UseToolbar": boolean;

    /**
     * HideToolbarSeparator will hide the toolbar separator
     */
    "HideToolbarSeparator": boolean;

    /**
     * ShowToolbarWhenFullscreen will keep the toolbar visible when the window is in fullscreen mode
     */
    "ShowToolbarWhenFullscreen": boolean;

    /**
     * ToolbarStyle is the style of toolbar to use
     */
    "ToolbarStyle": MacToolbarStyle;
}

/**
 * MacToolbarStyle is the style of toolbar for macOS
 */
export enum MacToolbarStyle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * MacToolbarStyleAutomatic - The default value. The style will be determined by the window's given configuration
     */
    MacToolbarStyleAutomatic = 0,

    /**
     * MacToolbarStyleExpanded - The toolbar will appear below the window title
     */
    MacToolbarStyleExpanded = 1,

    /**
     * MacToolbarStylePreference - The toolbar will appear below the window title and the items in the toolbar will attempt to have equal widths when possible
     */
    MacToolbarStylePreference = 2,

    /**
     * MacToolbarStyleUnified - The window title will appear inline with the toolbar when visible
     */
    MacToolbarStyleUnified = 3,

    /**
     * MacToolbarStyleUnifiedCompact - Same as MacToolbarStyleUnified, but with reduced margins in the toolbar allowing more focus to be on the contents of the window
     */
    MacToolbarStyleUnifiedCompact = 4,
};

/**
 * MacWebviewPreferences contains preferences for the Mac webview
 */
export interface MacWebviewPreferences {
    /**
     * TabFocusesLinks will enable tabbing to links
     */
    "TabFocusesLinks": u$0.Bool;

    /**
     * TextInteractionEnabled will enable text interaction
     */
    "TextInteractionEnabled": u$0.Bool;

    /**
     * FullscreenEnabled will enable fullscreen
     */
    "FullscreenEnabled": u$0.Bool;

    /**
     * AllowsBackForwardNavigationGestures enables horizontal swipe gestures for back/forward navigation
     */
    "AllowsBackForwardNavigationGestures": u$0.Bool;
}

/**
 * MacWindow contains macOS specific options for Webview Windows
 */
export interface MacWindow {
    /**
     * Backdrop is the backdrop type for the window
     */
    "Backdrop": MacBackdrop;

    /**
     * DisableShadow will disable the window shadow
     */
    "DisableShadow": boolean;

    /**
     * TitleBar contains options for the Mac titlebar
     */
    "TitleBar": MacTitleBar;

    /**
     * Appearance is the appearance type for the window
     */
    "Appearance": MacAppearanceType;

    /**
     * InvisibleTitleBarHeight defines the height of an invisible titlebar which responds to dragging
     */
    "InvisibleTitleBarHeight": number;

    /**
     * Maps events from platform specific to common event types
     */
    "EventMapping": { [_: `${number}`]: events$0.WindowEventType } | null;

    /**
     * EnableFraudulentWebsiteWarnings will enable warnings for fraudulent websites.
     * Default: false
     */
    "EnableFraudulentWebsiteWarnings": boolean;

    /**
     * WebviewPreferences contains preferences for the webview
     */
    "WebviewPreferences": MacWebviewPreferences;

    /**
     * WindowLevel sets the window level to control the order of windows in the screen
     */
    "WindowLevel": MacWindowLevel;

    /**
     * LiquidGlass contains configuration for the Liquid Glass effect
     */
    "LiquidGlass": MacLiquidGlass;
}

export enum MacWindowLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MacWindowLevelNormal = "normal",
    MacWindowLevelFloating = "floating",
    MacWindowLevelTornOffMenu = "tornOffMenu",
    MacWindowLevelModalPanel = "modalPanel",
    MacWindowLevelMainMenu = "mainMenu",
    MacWindowLevelStatus = "status",
    MacWindowLevelPopUpMenu = "popUpMenu",
    MacWindowLevelScreenSaver = "screenSaver",
};

export interface Menu {
}

export interface MenuBarTheme {
    /**
     * Default is the default theme
     */
    "Default": TextTheme | null;

    /**
     * Hover defines the theme to use when the menu item is hovered
     */
    "Hover": TextTheme | null;

    /**
     * Selected defines the theme to use when the menu item is selected
     */
    "Selected": TextTheme | null;
}

/**
 * MenuManager manages menu-related operations
 */
export interface MenuManager {
}

/**
 * NSVisualEffectMaterial represents the NSVisualEffectMaterial enum for macOS
 */
export enum NSVisualEffectMaterial {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * NSVisualEffectMaterial values from macOS SDK
     */
    NSVisualEffectMaterialAppearanceBased = 0,
    NSVisualEffectMaterialLight = 1,
    NSVisualEffectMaterialDark = 2,
    NSVisualEffectMaterialTitlebar = 3,
    NSVisualEffectMaterialSelection = 4,
    NSVisualEffectMaterialMenu = 5,
    NSVisualEffectMaterialPopover = 6,
    NSVisualEffectMaterialSidebar = 7,
    NSVisualEffectMaterialHeaderView = 10,
    NSVisualEffectMaterialSheet = 11,
    NSVisualEffectMaterialWindowBackground = 12,
    NSVisualEffectMaterialHUDWindow = 13,
    NSVisualEffectMaterialFullScreenUI = 15,
    NSVisualEffectMaterialToolTip = 17,
    NSVisualEffectMaterialContentBackground = 18,
    NSVisualEffectMaterialUnderWindowBackground = 21,
    NSVisualEffectMaterialUnderPageBackground = 22,

    /**
     * Use auto-selection based on Style
     */
    NSVisualEffectMaterialAuto = -1,
};

export interface RGBA {
    "Red": number;
    "Green": number;
    "Blue": number;
    "Alpha": number;
}

export interface ScreenManager {
}

/**
 * SystemTrayManager manages system tray-related operations
 */
export interface SystemTrayManager {
}

export interface TextTheme {
    /**
     * Text is the colour of the text
     */
    "Text": number | null;

    /**
     * Background is the background colour of the text
     */
    "Background": number | null;
}

export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * SystemDefault will use whatever the system theme is. The application will follow system theme changes.
     */
    SystemDefault = 0,

    /**
     * Dark Mode
     */
    Dark = 1,

    /**
     * Light Mode
     */
    Light = 2,
};

/**
 * ThemeSettings defines custom colours to use in dark or light mode.
 * They may be set using the hex values: 0x00BBGGRR
 */
export interface ThemeSettings {
    /**
     * Dark mode active window
     */
    "DarkModeActive": WindowTheme | null;

    /**
     * Dark mode inactive window
     */
    "DarkModeInactive": WindowTheme | null;

    /**
     * Light mode active window
     */
    "LightModeActive": WindowTheme | null;

    /**
     * Light mode inactive window
     */
    "LightModeInactive": WindowTheme | null;

    /**
     * Dark mode MenuBar
     */
    "DarkModeMenuBar": MenuBarTheme | null;

    /**
     * Light mode MenuBar
     */
    "LightModeMenuBar": MenuBarTheme | null;
}

/**
 * WebviewGpuPolicy values used for determining the webview's hardware acceleration policy.
 */
export enum WebviewGpuPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * WebviewGpuPolicyAlways Hardware acceleration is always enabled.
     */
    WebviewGpuPolicyAlways = 0,

    /**
     * WebviewGpuPolicyOnDemand Hardware acceleration is enabled/disabled as request by web contents.
     */
    WebviewGpuPolicyOnDemand = 1,

    /**
     * WebviewGpuPolicyNever Hardware acceleration is always disabled.
     */
    WebviewGpuPolicyNever = 2,
};

export interface WebviewWindowOptions {
    /**
     * Name is a unique identifier that can be given to a window.
     */
    "Name": string;

    /**
     * Title is the title of the window.
     */
    "Title": string;

    /**
     * Width is the starting width of the window.
     */
    "Width": number;

    /**
     * Height is the starting height of the window.
     */
    "Height": number;

    /**
     * AlwaysOnTop will make the window float above other windows.
     */
    "AlwaysOnTop": boolean;

    /**
     * URL is the URL to load in the window.
     */
    "URL": string;

    /**
     * DisableResize will disable the ability to resize the window.
     */
    "DisableResize": boolean;

    /**
     * Frameless will remove the window frame.
     */
    "Frameless": boolean;

    /**
     * MinWidth is the minimum width of the window.
     */
    "MinWidth": number;

    /**
     * MinHeight is the minimum height of the window.
     */
    "MinHeight": number;

    /**
     * MaxWidth is the maximum width of the window.
     */
    "MaxWidth": number;

    /**
     * MaxHeight is the maximum height of the window.
     */
    "MaxHeight": number;

    /**
     * StartState indicates the state of the window when it is first shown.
     * Default: WindowStateNormal
     */
    "StartState": WindowState;

    /**
     * BackgroundType is the type of background to use for the window.
     * Default: BackgroundTypeSolid
     */
    "BackgroundType": BackgroundType;

    /**
     * BackgroundColour is the colour to use for the window background.
     */
    "BackgroundColour": RGBA;

    /**
     * HTML is the HTML to load in the window.
     */
    "HTML": string;

    /**
     * JS is the JavaScript to load in the window.
     */
    "JS": string;

    /**
     * CSS is the CSS to load in the window.
     */
    "CSS": string;

    /**
     * Initial Position
     */
    "InitialPosition": WindowStartPosition;

    /**
     * X is the starting X position of the window.
     */
    "X": number;

    /**
     * Y is the starting Y position of the window.
     */
    "Y": number;

    /**
     * Hidden will hide the window when it is first created.
     */
    "Hidden": boolean;

    /**
     * Zoom is the zoom level of the window.
     */
    "Zoom": number;

    /**
     * ZoomControlEnabled will enable the zoom control.
     */
    "ZoomControlEnabled": boolean;

    /**
     * EnableDragAndDrop will enable drag and drop.
     */
    "EnableDragAndDrop": boolean;

    /**
     * OpenInspectorOnStartup will open the inspector when the window is first shown.
     */
    "OpenInspectorOnStartup": boolean;

    /**
     * Mac options
     */
    "Mac": MacWindow;

    /**
     * Windows options
     */
    "Windows": WindowsWindow;

    /**
     * Linux options
     */
    "Linux": LinuxWindow;

    /**
     * Toolbar button states
     */
    "MinimiseButtonState": ButtonState;
    "MaximiseButtonState": ButtonState;
    "CloseButtonState": ButtonState;

    /**
     * If true, the window's devtools will be available (default true in builds without the `production` build tag)
     */
    "DevToolsEnabled": boolean;

    /**
     * If true, the window's default context menu will be disabled (default false)
     */
    "DefaultContextMenuDisabled": boolean;

    /**
     * KeyBindings is a map of key bindings to functions
     */
    "KeyBindings": { [_: string]: any } | null;

    /**
     * IgnoreMouseEvents will ignore mouse events in the window (Windows + Mac only)
     */
    "IgnoreMouseEvents": boolean;

    /**
     * ContentProtectionEnabled specifies whether content protection is enabled, preventing screen capture and recording.
     * Effective on Windows and macOS only; no-op on Linux.
     * Best-effort protection with platform-specific caveats (see docs).
     */
    "ContentProtectionEnabled": boolean;
}

/**
 * WindowManager manages all window-related operations
 */
export interface WindowManager {
}

export enum WindowStartPosition {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    WindowCentered = 0,
    WindowXY = 1,
};

export enum WindowState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    WindowStateNormal = 0,
    WindowStateMinimised = 1,
    WindowStateMaximised = 2,
    WindowStateFullscreen = 3,
};

export interface WindowTheme {
    /**
     * BorderColour is the colour of the window border
     */
    "BorderColour": number | null;

    /**
     * TitleBarColour is the colour of the window title bar
     */
    "TitleBarColour": number | null;

    /**
     * TitleTextColour is the colour of the window title text
     */
    "TitleTextColour": number | null;
}

export interface WindowsWindow {
    /**
     * Select the type of translucent backdrop. Requires Windows 11 22621 or later.
     * Only used when window's `BackgroundType` is set to `BackgroundTypeTranslucent`.
     * Default: Auto
     */
    "BackdropType": BackdropType;

    /**
     * Disable the icon in the titlebar
     * Default: false
     */
    "DisableIcon": boolean;

    /**
     * Theme (Dark / Light / SystemDefault)
     * Default: SystemDefault - The application will follow system theme changes.
     */
    "Theme": Theme;

    /**
     * Specify custom colours to use for dark/light mode
     * Default: nil
     */
    "CustomTheme": ThemeSettings;

    /**
     * Disable all window decorations in Frameless mode, which means no "Aero Shadow" and no "Rounded Corner" will be shown.
     * "Rounded Corners" are only available on Windows 11.
     * Default: false
     */
    "DisableFramelessWindowDecorations": boolean;

    /**
     * WindowMask is used to set the window shape. Use a PNG with an alpha channel to create a custom shape.
     * Default: nil
     */
    "WindowMask": string | null;

    /**
     * WindowMaskDraggable is used to make the window draggable by clicking on the window mask.
     * Default: false
     */
    "WindowMaskDraggable": boolean;

    /**
     * ResizeDebounceMS is the amount of time to debounce redraws of webview2
     * when resizing the window
     * Default: 0
     */
    "ResizeDebounceMS": number;

    /**
     * WindowDidMoveDebounceMS is the amount of time to debounce the WindowDidMove event
     * when moving the window
     * Default: 0
     */
    "WindowDidMoveDebounceMS": number;

    /**
     * Event mapping for the window. This allows you to define a translation from one event to another.
     * Default: nil
     */
    "EventMapping": { [_: `${number}`]: events$0.WindowEventType } | null;

    /**
     * HiddenOnTaskbar hides the window from the taskbar
     * Default: false
     */
    "HiddenOnTaskbar": boolean;

    /**
     * EnableSwipeGestures enables swipe gestures for the window
     * Default: false
     */
    "EnableSwipeGestures": boolean;

    /**
     * Menu is the menu to use for the window.
     */
    "Menu": Menu | null;

    /**
     * Drag Cursor Effects
     */
    "OnEnterEffect": DragEffect;
    "OnOverEffect": DragEffect;

    /**
     * Permissions map for WebView2. If empty, default permissions will be granted.
     */
    "Permissions": { [_: `${number}`]: CoreWebView2PermissionState } | null;

    /**
     * ExStyle is the extended window style
     */
    "ExStyle": number;

    /**
     * GeneralAutofillEnabled enables general autofill
     */
    "GeneralAutofillEnabled": boolean;

    /**
     * PasswordAutosaveEnabled enables autosaving passwords
     */
    "PasswordAutosaveEnabled": boolean;

    /**
     * EnabledFeatures, DisabledFeatures and AdditionalLaunchArgs are used to enable or disable specific features in the WebView2 browser.
     * Available flags: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/webview-features-flags?tabs=dotnetcsharp#available-webview2-browser-flags
     * WARNING: Apps in production shouldn't use WebView2 browser flags,
     * because these flags might be removed or altered at any time,
     * and aren't necessarily supported long-term.
     * AdditionalLaunchArgs should always be preceded by "--"
     */
    "EnabledFeatures": string[] | null;
    "DisabledFeatures": string[] | null;
    "AdditionalLaunchArgs": string[] | null;
}
